export const Screens = {
  SplashScreen: 'SplashScreen',
  FeatureScreen1: 'FeatureScreen1',
  FeatureScreen2: 'FeatureScreen2',
  SignUpScreen: 'SignUpScreen',
  SignInScreen: 'SignInScreen',
  EmailVerificationScreen: 'EmailVerificationScreen',
  MobileVerificationScreen: 'MobileVerificationScreen',
  SetLocationScreen: 'SetLocationScreen',
  UserBioDataScreen: 'UserBioDataScreen',
  PaymentMethodScreen: 'PaymentMethodScreen',
  UploadPhotoScreen: 'UploadPhotoScreen',
  UploadPreviewScreen: 'UploadPreviewScreen',
  SuccessScreen: 'SuccessScreen',
  ForgotPassMethodScreen: 'ForgotPassMethodScreen',
  ResetPasseordScreen: 'ResetPasseordScreen',
  HomeScreen: 'HomeScreen',
  ProfileScreen: 'ProfileScreen',
  ShopScreen: 'ShopScreen',
  ChatScreen: 'ChatScreen',
  BottomTab: 'BottomTab',
  ChattingScreen: 'ChattingScreen',
};
