export const String = {
  App_Title_1: 'FoodNinja',
  App_Title_2: 'Deliever Favorite Food',
  Feature_1_T1: 'Find your Comfort',
  Feature_1_T2: 'Food hear',
  Feature_1_D1: 'Here You Can find a chef or dish for every',
  Feature_1_D2: 'taste and color. Enjoy!',
  Next: 'Next',
  Feature_2_T1: 'Food Ninja is Where Your',
  Feature_2_T2: 'Comfort Food Lives',
  Feature_2_D1: 'Enjoy a fast and smooth food delivery at',
  Feature_2_D2: 'your doorstep',
  Sign_Up_For_Free: 'Sign Up For Free ',
  Anamwp: 'Anamwp . . |',
  Email: 'Email',
  Password: 'Password',
  Confirm_Password: 'Confirm Password',
  Keep_Me_Signed_In: 'Keep Me Signed In',
  Email_Me_About_Special_Pricing: 'Email Me About Special Pricing',
  Already_Have_An_Account: 'already have an account?',
  Create_Account: 'Create Account',
  Login_To_Your_Account: 'Login To Your Account',
  Or_Continue_With: 'Or Continue With',
  Forgot_Your_Password: 'Forgot Your Password?',
  Facebook: 'Facebook',
  Google: 'Google',
  Login: 'Login',
  Forgot_Password: 'Forgot password?',
  Forgot_Discreption:
    'Select which contact details should we use to reset your password',
  Via_SMS: 'Via sms:',
  Via_EMAIL: 'Via email:',
  OTP_Screen_T1: 'Enter 4-digit',
  OTP_Screen_T2: 'Verification code',
  OTP_Screen_D1: 'Code send to ',
  OTP_Screen_D2: 'This code will expired in ',
  ResetPass_Screen_Title: 'Reset your password here',
  ResetPass_Screen_D1: 'Select which contact details should we ',
  ResetPass_Screen_D2: 'use to reset your password',
  Save: 'Save',
  Finish: 'Finish',
  Congrats: 'Congrats!',
  Reset_Pass_Success_msg: 'Password reset succesful',
  Back: 'Back',
  BioData_Screen_T1: 'Fill in your bio to get',
  BioData_Screen_T2: 'started',
  Security_D1: 'This data will be displayed in your account',
  Security_D2: 'profile for security',
  FirstName: 'First Name',
  LastName: 'Last Name',
  MobileNo: 'mobile Number',
  Payment_Method: 'Payment Method',
  UploadPhoto_Screen_T1: 'Upload Your Photo ',
  UploadPhoto_Screen_T2: 'Profile',
  From_Gallery: 'From Gallery',
  Take_Photo: 'Take Photo',
  Set_Your_Location: 'Set Your Location',
  Your_Location: 'Your Location',
  Set_Location: 'Set Location',
  Profile_Success_Msg: 'Your Profile Is Ready To Use',
  Find_Your: 'Find Your',
  Favourite_Food: 'Favourite Food',
  Search_Hint: 'What do you want to order?',
  Offer: 'Special Deal For',
  View_More: 'View More',
  Buy_Now: 'Buy Now',
  Nearest_Restaurant: 'Nearest Restaurant',
  Popular_Menu: 'Popular Menu',
  Home: 'Home',
  Profile: 'Profile',
  Shop: 'Shop',
  Chat: 'Chat',
  Less: 'View Less',
};
